version: '3.2'

services:
        elastic-01:
                image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
                container_name: elastic-01
                environment:
                        - node.name=elastic-01 
                        - cluster.name=docker-cluster-elk
                        - discovery.seed_hosts=elastic-01
                        - cluster.initial_master_nodes=elastic-01
                ulimits:
                        memlock:
                                soft: -1
                                hard: -1
                volumes: 
                        - ./data01:/usr/share/elasticsearch/data
                ports: 
                        - "9200:9200"
                networks: 
                        - elastic
                
        kibana:
                image: docker.elastic.co/kibana/kibana:7.5.2
                ports: 
                        - 5601:5601
                environment: 
                        ELASTICSEARCH_URL: http://elastic-01:9200
                        ELASTICSEARCH_HOSTS: http://elastic-01:9200
                networks: 
                        - elastic

        # logstash:
        #         build: 
        #                 context: ./logstash
        #         ports: 
        #                 - 5000:5000/tcp
        #                 - 5000:5000/udp
        #                 - 9600:9600
        #         environment: 
        #                 LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        #         networks: 
        #                 - elastic
        #         depends_on: 
        #                 - elastic-01

        # filebeat:
        #         build: 
        #                 context: ./filebeat
        #         networks: 
        #                 - elastic
        #         depends_on: 
        #                 - elastic-01
        #                 - logstash

networks: 
        elastic:
                driver: bridge
        

