version: '3'

services:
        elastic-01:
                image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
                container_name: elastic-01
                environment:
                        - node.name=elastic-01 
                        - cluster.name=docker-cluster-elk
                        - discovery.seed_hosts=elastic-01
                        - cluster.initial_master_nodes=elastic-01
                ulimits:
                        memlock:
                                soft: -1
                                hard: -1
                volumes: 
                        - ./data01:/usr/share/elasticsearch/data
                ports: 
                        - "9200:9200"
                networks: 
                        - elastic
                
        kibana:
                image: docker.elastic.co/kibana/kibana:7.5.2
                ports: 
                        - 5601:5601
                environment: 
                        ELASTICSEARCH_URL: http://elastic-01:9200
                        ELASTICSEARCH_HOSTS: http://elastic-01:9200
                networks: 
                        - elastic

networks: 
        elastic:
                driver: bridge
        

